[general]
import = [
    "~/.config/alacritty/themes/themes/aura.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1.66"

[keyboard]
bindings = [
{ key = "Return", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "R", mods = "Alt", chars = ". ranger\n" },
# { key = "A", mods = "Control|Shift", chars = "ls -la\n" },
# { key = "A", mods = "Control|Shift", chars = ". ranger\n" },
# { key = "P", mods = "Alt", command = { program = "xrandr-invert-colors"} },  
# { key = "Return", mods = "Control|Shift", command = { program = "alacritty", args = ["-e", "ranger"] } },
{ key = "L", mods = "Control|Shift", chars = "l" },
# { key = "Return", mods = "Control|Shift", mode = "Vi|Search|Alt|AppCursor|AppKeypad", action = "CreateNewWindow"},

{ key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
{ key = "_", mods = "Shift|Control", action = "DecreaseFontSize" },
{ key = "Key0", mods = "Control|Shift", action = "ResetFontSize" },
]


[window]
# opacity = 0.9
padding.x = 10
padding.y = 10
decorations = "Full"
decorations_theme_variant = "Dark"

[font]
# normal.family = "Cascadia Code PL"
# bold.family = "Cascadia Code PL"
# italic.family = "Cascadia Code PL"
# bold_italic.family = "Cascadia Code PL"
#IncreaseFontSize
#DecreaseFontSize
#ResetFontSize
size = 10
