#!/usr/bin/env bash
set -exo pipefail

# Computer winks at you
#curBrightness=$(brightnessctl get)
#brightnessctl set 0
#sleep 0.1
#brightnessctl set $curBrightness

# Computer throws a flashbang at you
xrandr-invert-colors
sleep 0.1
xrandr-invert-colors


ffplay -v 0 -nodisp -autoexit -af "volume=0.3" ~/.flash.mp3
