#!/usr/bin/env bash
set -exo pipefail

# Computer winks at you
#curBrightness=$(brightnessctl get)
#brightnessctl set 0
#sleep 0.1
#brightnessctl set $curBrightness

# Computer throws a flashbang at you
xcalib -invert -alter
sleep 0.1
xcalib -invert -alter


ffplay -v 0 -nodisp -autoexit -af "volume=0.3" ~/.flash.mp3
